#!/usr/bin/env python3

import handler

def run(): 
    parser = handler.build_parser()
    args = parser.parse_args()

    res = args.run_command()
    print(res)





if __name__ == "__main__":
    run()